name: Keepers Robinhood contracts
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'execution/gethexec/**'
      - 'broadcastclient/**'
      - 'arbnode/transaction_streamer.go'
      - 'go-ethereum'
      - 'keepers/**'
      - 'system_tests/keepers_test.go'
      - '.github/workflows/keepers.yml'
permissions:
  contents: read
jobs:
  contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build native Nitro and run Keepers tests
        run: keepers/deploy/test.sh
